In [ ]:
import numpy as np

IPython console for SymPy 1.14.0 (Python 3.13.9-64-bit) (ground types: python)

These commands were executed:
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.14.0/



# 第1章 矩阵

## 矩阵的概念


【课本知识点】矩阵的定义；单位矩阵、对角矩阵、数量矩阵、上 / 下三角矩阵、对称矩阵的结构与性质。

### ✍️伴读札记

#### 🔢NumPy


In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.diag([2, 4, 6])

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [7]:
np.random.randint(0, 10, size=(3,3))

array([[5, 6, 1],
       [7, 5, 7],
       [0, 0, 5]])

## 矩阵的运算

【课本知识点】矩阵加法、数乘的定义与运算律（交换律、结合律、分配律）。

【课本知识点】矩阵乘法的定义、运算律（重点：不满足交换律）；方阵的幂运算规则。

### ✍️伴读札记



#### 🔢NumPy

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
K = 3
np.array_equal(K*(A+B), K*A + K*B)

True

矩阵乘法用@运算符或np.dot()

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

A@B, A.dot(B), B@A, B.dot(A)

(array([[ 4,  4],
        [10,  8]]),
 array([[ 4,  4],
        [10,  8]]),
 array([[ 2,  4],
        [ 7, 10]]),
 array([[ 2,  4],
        [ 7, 10]]))

方阵幂用np.linalg.matrix_power()

In [14]:
np.linalg.matrix_power(A, 3)

array([[ 37,  54],
       [ 81, 118]])

In [15]:
A.T, A.T.T

(array([[1, 3],
        [2, 4]]),
 array([[1, 2],
        [3, 4]]))


## 分块矩阵





### ✍️伴读札记




#### 🔢NumPy

In [25]:
A = np.array([[1,2,0,0], [3,4,0,0],
               [0,0,5,6], [0,0,7,8]]);A

array([[1, 2, 0, 0],
       [3, 4, 0, 0],
       [0, 0, 5, 6],
       [0, 0, 7, 8]])

In [27]:
A11 = A[:2,:2]; A12 = A[:2,2:]
A21 = A[2:,:2]; A22 = A[2:,2:]

In [26]:
B = np.array(
    [[1,0,0,0], [0,1,0,0],
     [0,0,2,0], [0,0,0,2]]);B

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2]])

In [28]:
B11 = B[:2,:2]; B12 = B[:2,2:]
B21 = B[2:,:2]; B22 = B[2:,2:]

In [30]:
block_res = np.zeros_like(A)
block_res[:2,:2] = A11 @ B11
block_res[2:,2:] = A22 @ B22

In [32]:
np.array_equal(A@B, block_res)

True

# 习 题 一

1. 设 $x_1\begin{bmatrix} 1 \\ 1 \end{bmatrix} + x_2\begin{bmatrix} 1 \\ -1 \end{bmatrix} = \begin{bmatrix} 2 \\ 3 \end{bmatrix}$，求实数 $x_1, x_2$.

2. 设矩阵 $A, B$ 和 $C$ 满足 $3(A+C) = 2(B-C)$，其中，
$$A = \begin{bmatrix} 2 & 3 & 6 \\ -1 & 3 & 5 \end{bmatrix}, \quad B = \begin{bmatrix} 3 & 2 & 4 \\ 1 & -3 & 5 \end{bmatrix},$$
求矩阵 $C$.

3. 计算下列矩阵的乘积：
(1) $\begin{bmatrix} 1 \\ -1 \\ 2 \\ 3 \end{bmatrix} \begin{bmatrix} 3, 2, -1, 0 \end{bmatrix}$;
(2) $[1, 2, 3] \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$;
(3) $\begin{bmatrix} 4 & 3 & 1 \\ 1 & -2 & 3 \\ 5 & 7 & 0 \end{bmatrix} \begin{bmatrix} 7 \\ 2 \\ 1 \end{bmatrix}$;
(4) $[x_1, x_2, x_3] \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}$;
(5) $\begin{bmatrix} 2 & 1 & 4 & 0 \\ 1 & -1 & 3 & 4 \end{bmatrix} \begin{bmatrix} 1 & 3 & 1 \\ 0 & -1 & 2 \\ 1 & -3 & 1 \\ 4 & 0 & -2 \end{bmatrix}$;
(6) $\begin{bmatrix} 1 & 2 & 1 & 0 \\ 0 & 1 & 0 & 1 \\ 0 & 0 & 2 & 1 \\ 0 & 0 & 0 & 3 \end{bmatrix} \begin{bmatrix} 1 & 0 & 3 & 1 \\ 0 & 1 & 2 & -1 \\ 0 & 0 & -2 & 3 \\ 0 & 0 & 0 & -3 \end{bmatrix}$.

4. 设 $A = \begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix}, B = \begin{bmatrix} 1 & 0 \\ 1 & 2 \end{bmatrix}$，通过计算判断下列各式是否成立：
(1) $AB = BA$;
(2) $(A+B)(A-B) = A^2 - B^2$;
(3) $(A+B)^2 = A^2 + 2AB + B^2$.

5. 举例说明下列命题是错误的：
(1) 若 $A^2 = O$，则 $A = O$;
(2) 若 $A^2 = A$，则 $A = O$ 或 $A = E$;
(3) 若 $AX = AY$ 且 $A \neq O$，则 $X = Y$.

6. 设 $A = \begin{bmatrix} \lambda & 1 & 0 \\ 0 & \lambda & 1 \\ 0 & 0 & \lambda \end{bmatrix}$，计算 $A^k$ ($k$ 为正整数).

7. 设 $A = \begin{bmatrix} 2 & -1 & 0 \\ 1 & 3 & 1 \end{bmatrix}, B = \begin{bmatrix} 2 & 1 \\ -3 & 5 \\ 2 & 4 \end{bmatrix}$，求 $(AB)^T$ 及 $B^T A^T$.

8. 设 $A, B$ 为 $n$ 阶矩阵，且 $A$ 为对称阵，证明：$B^T AB$ 也是对称阵.

9. 设 $A, B$ 为 $n$ 阶对称阵，证明：$AB$ 是对称阵的充分必要条件是 $AB = BA$.

10. 利用分块矩阵计算下列各题：
(1) $\begin{bmatrix} 1 & -1 & 0 & 0 & 0 \\ 0 & 2 & 0 & 0 & 0 \\ 1 & 0 & 3 & -1 & 1 \\ -1 & 1 & 2 & 0 & 0 \\ 2 & 1 & 1 & -1 & 1 \end{bmatrix} \begin{bmatrix} 3 & 1 & 1 & -1 & 1 \\ -2 & 0 & 0 & 2 & 1 \\ 0 & 0 & 1 & -1 & 0 \\ 0 & 0 & 0 & 0 & 1 \\ 0 & 0 & -1 & 1 & 1 \end{bmatrix}$;
(2) $\begin{bmatrix} 1 & 0 & 1 & 0 & 0 \\ 0 & 2 & -1 & 0 & 0 \\ 3 & 1 & 0 & 0 & 0 \\ 0 & 0 & 0 & -2 & 0 \\ 0 & 0 & 0 & 0 & -2 \end{bmatrix} \begin{bmatrix} 1 & 0 & 1 & 0 & 0 \\ 0 & 2 & 0 & 0 & 0 \\ 0 & 0 & 3 & 0 & 0 \\ 0 & 0 & 0 & -1 & 3 \\ 0 & 0 & 0 & 4 & 2 \end{bmatrix}$.

以下是根据图片内容整理的全部习题解答，包含解题思路（简述使用的定义、定理、定律和公式）和详细的解答过程。所有数学公式均使用 `$$` 包裹。

---

### 习 题 一

#### 1. 设 $x_1 \begin{bmatrix} 1 \\ 1 \end{bmatrix} + x_2 \begin{bmatrix} 1 \\ -1 \end{bmatrix} = \begin{bmatrix} 2 \\ 3 \end{bmatrix}$，求实数 $x_1, x_2$.
**解题思路**：利用矩阵的数乘和加法运算，将等式转化为线性方程组求解。
**解答**：
原等式可化为：
$$ \begin{bmatrix} x_1 \\ x_1 \end{bmatrix} + \begin{bmatrix} x_2 \\ -x_2 \end{bmatrix} = \begin{bmatrix} x_1 + x_2 \\ x_1 - x_2 \end{bmatrix} = \begin{bmatrix} 2 \\ 3 \end{bmatrix} $$
由此得到方程组：
$$ \begin{cases} x_1 + x_2 = 2 \\ x_1 - x_2 = 3 \end{cases} $$
两式相加得 $2x_1 = 5 \implies x_1 = \frac{5}{2}$；两式相减得 $2x_2 = -1 \implies x_2 = -\frac{1}{2}$。
故 $x_1 = \frac{5}{2}, x_2 = -\frac{1}{2}$。

#### 2. 设矩阵 $A, B$ 和 $C$ 满足 $3(A+C) = 2(B-C)$，其中，$A = \begin{bmatrix} 2 & 3 & 6 \\ -1 & 3 & 5 \end{bmatrix}, B = \begin{bmatrix} 3 & 2 & 4 \\ 1 & -3 & 5 \end{bmatrix}$，求矩阵 $C$.
**解题思路**：利用矩阵的加减法和数乘运算，先通过移项合并同类项解出 $C$ 的表达式，再代入数值计算。
**解答**：
由 $3(A+C) = 2(B-C)$ 展开得：
$$ 3A + 3C = 2B - 2C \implies 5C = 2B - 3A \implies C = \frac{1}{5}(2B - 3A) $$
计算 $2B - 3A$：
$$ 2B = \begin{bmatrix} 6 & 4 & 8 \\ 2 & -6 & 10 \end{bmatrix}, \quad 3A = \begin{bmatrix} 6 & 9 & 18 \\ -3 & 9 & 15 \end{bmatrix} $$
$$ 2B - 3A = \begin{bmatrix} 6-6 & 4-9 & 8-18 \\ 2-(-3) & -6-9 & 10-15 \end{bmatrix} = \begin{bmatrix} 0 & -5 & -10 \\ 5 & -15 & -5 \end{bmatrix} $$
因此：
$$ C = \frac{1}{5} \begin{bmatrix} 0 & -5 & -10 \\ 5 & -15 & -5 \end{bmatrix} = \begin{bmatrix} 0 & -1 & -2 \\ 1 & -3 & -1 \end{bmatrix} $$

#### 3. 计算下列矩阵的乘积：
**解题思路**：根据矩阵乘法定义，若 $A$ 为 $m \times s$ 矩阵，$B$ 为 $s \times n$ 矩阵，则乘积 $C = AB$ 为 $m \times n$ 矩阵，其中 $c_{ij} = \sum_{k=1}^s a_{ik}b_{kj}$。

**(1)** $\begin{bmatrix} 1 \\ -1 \\ 2 \\ 3 \end{bmatrix} [3, 2, -1, 0]$
**解答**：为 $4 \times 1$ 与 $1 \times 4$ 矩阵相乘，结果为 $4 \times 4$ 矩阵。
$$ \begin{bmatrix} 1 \times 3 & 1 \times 2 & 1 \times (-1) & 1 \times 0 \\ -1 \times 3 & -1 \times 2 & -1 \times (-1) & -1 \times 0 \\ 2 \times 3 & 2 \times 2 & 2 \times (-1) & 2 \times 0 \\ 3 \times 3 & 3 \times 2 & 3 \times (-1) & 3 \times 0 \end{bmatrix} = \begin{bmatrix} 3 & 2 & -1 & 0 \\ -3 & -2 & 1 & 0 \\ 6 & 4 & -2 & 0 \\ 9 & 6 & -3 & 0 \end{bmatrix} $$

**(2)** $[1, 2, 3] \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$
**解答**：为 $1 \times 3$ 与 $3 \times 1$ 矩阵相乘，结果为 $1 \times 1$ 矩阵（标量）。
$$ 1 \times 1 + 2 \times 2 + 3 \times 3 = 1 + 4 + 9 = 14 $$

**(3)** $\begin{bmatrix} 4 & 3 & 1 \\ 1 & -2 & 3 \\ 5 & 7 & 0 \end{bmatrix} \begin{bmatrix} 7 \\ 2 \\ 1 \end{bmatrix}$
**解答**：为 $3 \times 3$ 与 $3 \times 1$ 矩阵相乘，结果为 $3 \times 1$ 矩阵。
$$ \begin{bmatrix} 4 \times 7 + 3 \times 2 + 1 \times 1 \\ 1 \times 7 + (-2) \times 2 + 3 \times 1 \\ 5 \times 7 + 7 \times 2 + 0 \times 1 \end{bmatrix} = \begin{bmatrix} 28 + 6 + 1 \\ 7 - 4 + 3 \\ 35 + 14 + 0 \end{bmatrix} = \begin{bmatrix} 35 \\ 6 \\ 49 \end{bmatrix} $$

**(4)** $[x_1, x_2, x_3] \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}$
**解答**：连续两次矩阵乘法，最终结果为 $1 \times 1$ 矩阵（二次型）。
先计算前两个矩阵乘积：
$$ [x_1 a_{11} + x_2 a_{21} + x_3 a_{31}, x_1 a_{12} + x_2 a_{22} + x_3 a_{32}, x_1 a_{13} + x_2 a_{23} + x_3 a_{33}] $$
再与 $\begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}$ 相乘：
$$ (x_1 a_{11} + x_2 a_{21} + x_3 a_{31})x_1 + (x_1 a_{12} + x_2 a_{22} + x_3 a_{32})x_2 + (x_1 a_{13} + x_2 a_{23} + x_3 a_{33})x_3 $$
展开并整理得：
$$ a_{11}x_1^2 + a_{22}x_2^2 + a_{33}x_3^2 + (a_{12}+a_{21})x_1x_2 + (a_{13}+a_{31})x_1x_3 + (a_{23}+a_{32})x_2x_3 $$

**(5)** $\begin{bmatrix} 2 & 1 & 4 & 0 \\ 1 & -1 & 3 & 4 \end{bmatrix} \begin{bmatrix} 1 & 3 & 1 \\ 0 & -1 & 2 \\ 1 & -3 & 1 \\ 4 & 0 & -2 \end{bmatrix}$
**解答**：为 $2 \times 4$ 与 $4 \times 3$ 矩阵相乘，结果为 $2 \times 3$ 矩阵。
第一行：
$2(1)+1(0)+4(1)+0(4) = 6$
$2(3)+1(-1)+4(-3)+0(0) = -7$
$2(1)+1(2)+4(1)+0(-2) = 8$
第二行：
$1(1)+(-1)(0)+3(1)+4(4) = 20$
$1(3)+(-1)(-1)+3(-3)+4(0) = -5$
$1(1)+(-1)(2)+3(1)+4(-2) = -6$
结果：$\begin{bmatrix} 6 & -7 & 8 \\ 20 & -5 & -6 \end{bmatrix}$

**(6)** $\begin{bmatrix} 1 & 2 & 1 & 0 \\ 0 & 1 & 0 & 1 \\ 0 & 0 & 2 & 1 \\ 0 & 0 & 0 & 3 \end{bmatrix} \begin{bmatrix} 1 & 0 & 3 & 1 \\ 0 & 1 & 2 & -1 \\ 0 & 0 & -2 & 3 \\ 0 & 0 & 0 & -3 \end{bmatrix}$
**解答**：两个上三角矩阵相乘，结果仍为上三角矩阵。
$c_{11} = 1 \times 1 = 1$
$c_{12} = 1 \times 0 + 2 \times 1 = 2$
$c_{13} = 1 \times 3 + 2 \times 2 + 1 \times (-2) = 5$
$c_{14} = 1 \times 1 + 2 \times (-1) + 1 \times 3 + 0 \times (-3) = 2$
$c_{22} = 1 \times 1 = 1$
$c_{23} = 1 \times 2 + 0 \times (-2) = 2$
$c_{24} = 1 \times (-1) + 0 \times 3 + 1 \times (-3) = -4$
$c_{33} = 2 \times (-2) = -4$
$c_{34} = 2 \times 3 + 1 \times (-3) = 3$
$c_{44} = 3 \times (-3) = -9$
结果：$\begin{bmatrix} 1 & 2 & 5 & 2 \\ 0 & 1 & 2 & -4 \\ 0 & 0 & -4 & 3 \\ 0 & 0 & 0 & -9 \end{bmatrix}$

#### 4. 设 $A = \begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix}, B = \begin{bmatrix} 1 & 0 \\ 1 & 2 \end{bmatrix}$，通过计算判断下列各式是否成立：
**解题思路**：直接进行矩阵乘法运算，验证等号两边是否相等。

**(1) $AB = BA$**
**解答**：
$$ AB = \begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix} \begin{bmatrix} 1 & 0 \\ 1 & 2 \end{bmatrix} = \begin{bmatrix} 2 & 2 \\ 1 & 2 \end{bmatrix} $$
$$ BA = \begin{bmatrix} 1 & 0 \\ 1 & 2 \end{bmatrix} \begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix} = \begin{bmatrix} 1 & 1 \\ 1 & 3 \end{bmatrix} $$
因为 $AB \neq BA$，所以**不成立**。

**(2) $(A+B)(A-B) = A^2 - B^2$**
**解答**：
$$ A+B = \begin{bmatrix} 2 & 1 \\ 1 & 3 \end{bmatrix}, \quad A-B = \begin{bmatrix} 0 & 1 \\ -1 & -1 \end{bmatrix} $$
$$ (A+B)(A-B) = \begin{bmatrix} 2 & 1 \\ 1 & 3 \end{bmatrix} \begin{bmatrix} 0 & 1 \\ -1 & -1 \end{bmatrix} = \begin{bmatrix} -1 & 1 \\ -3 & -2 \end{bmatrix} $$
$$ A^2 = \begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix} \begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix} = \begin{bmatrix} 1 & 2 \\ 0 & 1 \end{bmatrix}, \quad B^2 = \begin{bmatrix} 1 & 0 \\ 1 & 2 \end{bmatrix} \begin{bmatrix} 1 & 0 \\ 1 & 2 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 3 & 4 \end{bmatrix} $$
$$ A^2 - B^2 = \begin{bmatrix} 1 & 2 \\ 0 & 1 \end{bmatrix} - \begin{bmatrix} 1 & 0 \\ 3 & 4 \end{bmatrix} = \begin{bmatrix} 0 & 2 \\ -3 & -3 \end{bmatrix} $$
因为 $\begin{bmatrix} -1 & 1 \\ -3 & -2 \end{bmatrix} \neq \begin{bmatrix} 0 & 2 \\ -3 & -3 \end{bmatrix}$，所以**不成立**。
（注：因为 $AB \neq BA$，矩阵乘法没有平方差公式）

**(3) $(A+B)^2 = A^2 + 2AB + B^2$**
**解答**：
$$ (A+B)^2 = \begin{bmatrix} 2 & 1 \\ 1 & 3 \end{bmatrix} \begin{bmatrix} 2 & 1 \\ 1 & 3 \end{bmatrix} = \begin{bmatrix} 5 & 5 \\ 5 & 10 \end{bmatrix} $$
$$ A^2 + 2AB + B^2 = \begin{bmatrix} 1 & 2 \\ 0 & 1 \end{bmatrix} + 2\begin{bmatrix} 2 & 2 \\ 1 & 2 \end{bmatrix} + \begin{bmatrix} 1 & 0 \\ 3 & 4 \end{bmatrix} = \begin{bmatrix} 1 & 2 \\ 0 & 1 \end{bmatrix} + \begin{bmatrix} 4 & 4 \\ 2 & 4 \end{bmatrix} + \begin{bmatrix} 1 & 0 \\ 3 & 4 \end{bmatrix} = \begin{bmatrix} 6 & 6 \\ 5 & 9 \end{bmatrix} $$
因为 $\begin{bmatrix} 5 & 5 \\ 5 & 10 \end{bmatrix} \neq \begin{bmatrix} 6 & 6 \\ 5 & 9 \end{bmatrix}$，所以**不成立**。
（注：因为 $AB \neq BA$，矩阵乘法没有完全平方公式）

#### 5. 举例说明下列命题是错误的：
**解题思路**：寻找反例即可。

**(1) 若 $A^2 = O$，则 $A = O$;**
**解答**：令 $A = \begin{bmatrix} 0 & 1 \\ 0 & 0 \end{bmatrix}$，则 $A^2 = \begin{bmatrix} 0 & 1 \\ 0 & 0 \end{bmatrix} \begin{bmatrix} 0 & 1 \\ 0 & 0 \end{bmatrix} = \begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix} = O$。但 $A \neq O$。

**(2) 若 $A^2 = A$，则 $A = O$ 或 $A = E$;**
**解答**：令 $A = \begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix}$，则 $A^2 = \begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix} \begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix} = A$。但 $A \neq O$ 且 $A \neq E$。

**(3) 若 $AX = AY$ 且 $A \neq O$，则 $X = Y$.**
**解答**：令 $A = \begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix}, X = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}, Y = \begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix}$。
$$ AX = \begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix}, \quad AY = \begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix} $$
$AX = AY$ 且 $A \neq O$，但 $X \neq Y$。说明矩阵乘法不满足消去律。

#### 6. 设 $A = \begin{bmatrix} \lambda & 1 & 0 \\ 0 & \lambda & 1 \\ 0 & 0 & \lambda \end{bmatrix}$，计算 $A^k$ ($k$ 为正整数).
**解题思路**：利用矩阵拆分和二项式定理。$A = \lambda E + J$，其中 $J = \begin{bmatrix} 0 & 1 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix}$。因为 $\lambda E$ 与 $J$ 可交换，可使用二项式展开。
**解答**：
设 $J = \begin{bmatrix} 0 & 1 & 0 \\ 0 & 0 & 1 \\ 0 & 0 & 0 \end{bmatrix}$，则 $A = \lambda E + J$。
计算 $J$ 的幂次：
$$ J^2 = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}, \quad J^3 = O \quad (当 n \ge 3 时) $$
由二项式定理：
$$ A^k = (\lambda E + J)^k = \sum_{i=0}^k C_k^i (\lambda E)^{k-i} J^i = \lambda^k E + k \lambda^{k-1} J + \frac{k(k-1)}{2} \lambda^{k-2} J^2 $$
代入 $J$ 和 $J^2$ 得：
$$ A^k = \begin{bmatrix} \lambda^k & k\lambda^{k-1} & \frac{k(k-1)}{2}\lambda^{k-2} \\ 0 & \lambda^k & k\lambda^{k-1} \\ 0 & 0 & \lambda^k \end{bmatrix} \quad (k \ge 2) $$
（注：当 $k=1$ 时，第三项系数为 $0$，公式也成立；如果 $k=1$ 且 $\lambda=0$ 导致 $0 \cdot \lambda^{-1}$ 无意义，可视情况单独讨论，通常认为公式形式统一。）

#### 7. 设 $A = \begin{bmatrix} 2 & -1 & 0 \\ 1 & 3 & 1 \end{bmatrix}, B = \begin{bmatrix} 2 & 1 \\ -3 & 5 \\ 2 & 4 \end{bmatrix}$，求 $(AB)^T$ 及 $B^T A^T$.
**解题思路**：直接计算 $AB$ 再转置，并计算 $B^T$ 与 $A^T$ 的乘积，验证性质 $(AB)^T = B^T A^T$。
**解答**：
$$ AB = \begin{bmatrix} 2 & -1 & 0 \\ 1 & 3 & 1 \end{bmatrix} \begin{bmatrix} 2 & 1 \\ -3 & 5 \\ 2 & 4 \end{bmatrix} = \begin{bmatrix} 4+3+0 & 2-5+0 \\ 2-9+2 & 1+15+4 \end{bmatrix} = \begin{bmatrix} 7 & -3 \\ -5 & 20 \end{bmatrix} $$
$$ (AB)^T = \begin{bmatrix} 7 & -5 \\ -3 & 20 \end{bmatrix} $$
计算 $B^T A^T$：
$$ B^T = \begin{bmatrix} 2 & -3 & 2 \\ 1 & 5 & 4 \end{bmatrix}, \quad A^T = \begin{bmatrix} 2 & 1 \\ -1 & 3 \\ 0 & 1 \end{bmatrix} $$
$$ B^T A^T = \begin{bmatrix} 2 & -3 & 2 \\ 1 & 5 & 4 \end{bmatrix} \begin{bmatrix} 2 & 1 \\ -1 & 3 \\ 0 & 1 \end{bmatrix} = \begin{bmatrix} 4+3+0 & 2-9+2 \\ 2-5+0 & 1+15+4 \end{bmatrix} = \begin{bmatrix} 7 & -5 \\ -3 & 20 \end{bmatrix} $$
验证了性质：$(AB)^T = B^T A^T$。

#### 8. 设 $A, B$ 为 $n$ 阶矩阵，且 $A$ 为对称阵，证明：$B^T A B$ 也是对称阵.
**解题思路**：根据对称阵的定义，即证 $(B^T A B)^T = B^T A B$。利用转置的性质 $(XYZ)^T = Z^T Y^T X^T$。
**证明**：
$$ (B^T A B)^T = B^T A^T (B^T)^T = B^T A^T B $$
因为 $A$ 是对称阵，所以 $A^T = A$。代入得：
$$ (B^T A B)^T = B^T A B $$
故 $B^T A B$ 也是对称阵。证毕。

#### 9. 设 $A, B$ 为 $n$ 阶对称阵，证明：$AB$ 是对称阵的充分必要条件是 $AB=BA$.
**解题思路**：利用对称阵的定义和转置的性质。
**证明**：
必要性：若 $AB$ 是对称阵，则 $(AB)^T = AB$。又因为 $A, B$ 是对称阵，$(AB)^T = B^T A^T = BA$。因此 $AB = BA$。
充分性：若 $AB = BA$。则 $(AB)^T = B^T A^T = BA = AB$。因此 $AB$ 是对称阵。证毕。

#### 10. 利用分块矩阵计算下列各题：
**解题思路**：观察矩阵的零元素分布，将矩阵划分成合适的分块矩阵，特别是分块对角矩阵或分块三角矩阵，以简化计算。

**(1)** $\begin{bmatrix} 1 & -1 & 0 & 0 & 0 \\ 0 & 2 & 0 & 0 & 0 \\ 1 & 0 & 3 & -1 & 1 \\ -1 & 1 & 2 & 0 & 0 \\ 2 & 1 & 1 & -1 & 1 \end{bmatrix} \begin{bmatrix} 3 & 1 & 1 & -1 & 1 \\ -2 & 0 & 0 & 2 & 1 \\ 0 & 0 & 1 & -1 & 0 \\ 0 & 0 & 0 & 0 & 1 \\ 0 & 0 & -1 & 1 & 1 \end{bmatrix}$
**解答**：
将矩阵按 $2 \times 3$ 分块。设
$$ A = \begin{bmatrix} A_{11} & O \\ A_{21} & A_{22} \end{bmatrix}, \quad B = \begin{bmatrix} B_{11} & B_{12} \\ O & B_{22} \end{bmatrix} $$
其中：
$A_{11} = \begin{bmatrix} 1 & -1 \\ 0 & 2 \end{bmatrix}, A_{21} = \begin{bmatrix} 1 & 0 \\ -1 & 1 \\ 2 & 1 \end{bmatrix}, A_{22} = \begin{bmatrix} 3 & -1 & 1 \\ 2 & 0 & 0 \\ 1 & -1 & 1 \end{bmatrix}$
$B_{11} = \begin{bmatrix} 3 & 1 \\ -2 & 0 \end{bmatrix}, B_{12} = \begin{bmatrix} 1 & -1 & 1 \\ 0 & 2 & 1 \end{bmatrix}, B_{22} = \begin{bmatrix} 1 & -1 & 0 \\ 0 & 0 & 1 \\ -1 & 1 & 1 \end{bmatrix}$
则 $AB = \begin{bmatrix} A_{11}B_{11} & A_{11}B_{12} \\ A_{21}B_{11} & A_{21}B_{12} + A_{22}B_{22} \end{bmatrix}$。
计算各分块：
$A_{11}B_{11} = \begin{bmatrix} 1 & -1 \\ 0 & 2 \end{bmatrix} \begin{bmatrix} 3 & 1 \\ -2 & 0 \end{bmatrix} = \begin{bmatrix} 5 & 1 \\ -4 & 0 \end{bmatrix}$
$A_{11}B_{12} = \begin{bmatrix} 1 & -1 \\ 0 & 2 \end{bmatrix} \begin{bmatrix} 1 & -1 & 1 \\ 0 & 2 & 1 \end{bmatrix} = \begin{bmatrix} 1 & -3 & 0 \\ 0 & 4 & 2 \end{bmatrix}$
$A_{21}B_{11} = \begin{bmatrix} 1 & 0 \\ -1 & 1 \\ 2 & 1 \end{bmatrix} \begin{bmatrix} 3 & 1 \\ -2 & 0 \end{bmatrix} = \begin{bmatrix} 3 & 1 \\ -5 & -1 \\ 4 & 2 \end{bmatrix}$
$A_{21}B_{12} = \begin{bmatrix} 1 & 0 \\ -1 & 1 \\ 2 & 1 \end{bmatrix} \begin{bmatrix} 1 & -1 & 1 \\ 0 & 2 & 1 \end{bmatrix} = \begin{bmatrix} 1 & -1 & 1 \\ -1 & 3 & 0 \\ 2 & 0 & 3 \end{bmatrix}$
$A_{22}B_{22} = \begin{bmatrix} 3 & -1 & 1 \\ 2 & 0 & 0 \\ 1 & -1 & 1 \end{bmatrix} \begin{bmatrix} 1 & -1 & 0 \\ 0 & 0 & 1 \\ -1 & 1 & 1 \end{bmatrix} = \begin{bmatrix} 2 & -2 & 0 \\ 2 & -2 & 0 \\ 0 & 0 & 0 \end{bmatrix}$
$A_{21}B_{12} + A_{22}B_{22} = \begin{bmatrix} 1 & -1 & 1 \\ -1 & 3 & 0 \\ 2 & 0 & 3 \end{bmatrix} + \begin{bmatrix} 2 & -2 & 0 \\ 2 & -2 & 0 \\ 0 & 0 & 0 \end{bmatrix} = \begin{bmatrix} 3 & -3 & 1 \\ 1 & 1 & 0 \\ 2 & 0 & 3 \end{bmatrix}$
合并结果得：
$$ AB = \begin{bmatrix} 5 & 1 & 1 & -3 & 0 \\ -4 & 0 & 0 & 4 & 2 \\ 3 & 1 & 3 & -3 & 1 \\ -5 & -1 & 1 & 1 & 0 \\ 4 & 2 & 2 & 0 & 3 \end{bmatrix} $$

**(2)** $\begin{bmatrix} 1 & 0 & 1 & 0 & 0 \\ 0 & 2 & -1 & 0 & 0 \\ 3 & 1 & 0 & 0 & 0 \\ 0 & 0 & 0 & -2 & 0 \\ 0 & 0 & 0 & 0 & -2 \end{bmatrix} \begin{bmatrix} 1 & 0 & 1 & 0 & 0 \\ 0 & 2 & 0 & 0 & 0 \\ 0 & 0 & 3 & 0 & 0 \\ 0 & 0 & 0 & -1 & 3 \\ 0 & 0 & 0 & 4 & 2 \end{bmatrix}$
**解答**：
观察发现两个矩阵均为分块对角矩阵（前 $3$ 阶和后 $2$ 阶没有交叉项），设
$$ A = \begin{bmatrix} A_{11} & O \\ O & A_{22} \end{bmatrix}, \quad B = \begin{bmatrix} B_{11} & O \\ O & B_{22} \end{bmatrix} $$
其中：
$A_{11} = \begin{bmatrix} 1 & 0 & 1 \\ 0 & 2 & -1 \\ 3 & 1 & 0 \end{bmatrix}, A_{22} = \begin{bmatrix} -2 & 0 \\ 0 & -2 \end{bmatrix}$
$B_{11} = \begin{bmatrix} 1 & 0 & 1 \\ 0 & 2 & 0 \\ 0 & 0 & 3 \end{bmatrix}, B_{22} = \begin{bmatrix} -1 & 3 \\ 4 & 2 \end{bmatrix}$
则 $AB = \begin{bmatrix} A_{11}B_{11} & O \\ O & A_{22}B_{22} \end{bmatrix}$。
计算各分块：
$A_{11}B_{11} = \begin{bmatrix} 1 & 0 & 1 \\ 0 & 2 & -1 \\ 3 & 1 & 0 \end{bmatrix} \begin{bmatrix} 1 & 0 & 1 \\ 0 & 2 & 0 \\ 0 & 0 & 3 \end{bmatrix} = \begin{bmatrix} 1 & 0 & 1+3 \\ 0 & 4 & -3 \\ 3 & 2 & 3 \end{bmatrix} = \begin{bmatrix} 1 & 0 & 4 \\ 0 & 4 & -3 \\ 3 & 2 & 3 \end{bmatrix}$
$A_{22}B_{22} = \begin{bmatrix} -2 & 0 \\ 0 & -2 \end{bmatrix} \begin{bmatrix} -1 & 3 \\ 4 & 2 \end{bmatrix} = \begin{bmatrix} 2 & -6 \\ -8 & -4 \end{bmatrix}$
合并结果得：
$$ AB = \begin{bmatrix} 1 & 0 & 4 & 0 & 0 \\ 0 & 4 & -3 & 0 & 0 \\ 3 & 2 & 3 & 0 & 0 \\ 0 & 0 & 0 & 2 & -6 \\ 0 & 0 & 0 & -8 & -4 \end{bmatrix} $$

# 习题一 全题解答
> 预备知识：矩阵加法、数乘、矩阵乘法、转置、分块矩阵、对称矩阵定义；矩阵乘法**不满足交换律、消去律**。
> 矩阵乘法规则：若$A_{m\times s},B_{s\times n}$，则$\(C=AB\)$，$c_{ij}=\sum_{k=1}^s a_{ik}b_{kj}$；
> 转置性质：$(AB)^T=B^T A^T$；对称矩阵：$A^T=A$。

## 1. 设 $x_1\begin{bmatrix}1\\1\end{bmatrix}+x_2\begin{bmatrix}1\\-1\end{bmatrix}=\begin{bmatrix}2\\3\end{bmatrix}$，求实数 $x_1,x_2$
**思路**：向量线性组合，对应分量相等，得到线性方程组。
$$
\begin{cases}
x_1+x_2=2\\
x_1-x_2=3
\end{cases}
$$
两式相加：$2x_1=5\Rightarrow x_1=\dfrac52$；代入得 $x_2=2-\dfrac52=-\dfrac12$。
**答案**：$\boldsymbol{x_1=\dfrac52,\ x_2=-\dfrac12}$

---

## 2. $3(A+C)=2(B-C)$，已知
$A=\begin{bmatrix}2&3&6\\-1&3&5\end{bmatrix},\ B=\begin{bmatrix}3&2&4\\1&-3&5\end{bmatrix}$，求$C$
**思路**：矩阵方程移项，解出 $C$
$$
3A+3C=2B-2C \Rightarrow 5C=2B-3A \Rightarrow C=\frac15(2B-3A)
$$
$$
2B=\begin{bmatrix}6&4&8\\2&-6&10\end{bmatrix},\quad
3A=\begin{bmatrix}6&9&18\\-3&9&15\end{bmatrix}
$$
$$
2B-3A=\begin{bmatrix}0&-5&-10\\5&-15&-5\end{bmatrix}
$$
$$
C=\frac15\begin{bmatrix}0&-5&-10\\5&-15&-5\end{bmatrix}=
\boldsymbol{\begin{bmatrix}0&-1&-2\\1&-3&-1\end{bmatrix}}
$$

---

## 3. 矩阵乘积计算
### (1) $\begin{bmatrix}1\\-1\\2\\3\end{bmatrix}[3,\ 2,\ -1,\ 0]$
**思路**：$4\times1$矩阵乘$1\times4$矩阵，结果$4\times4$矩阵。
$$
=\boldsymbol{\begin{bmatrix}
3&2&-1&0\\
-3&-2&1&0\\
6&4&-2&0\\
9&6&-3&0
\end{bmatrix}}
$$

### (2) $[1,\ 2,\ 3]\begin{bmatrix}1\\2\\3\end{bmatrix}$
**思路**：$1\times3$乘$3\times1$，结果$1\times1$矩阵（数）
$$
=1\times1+2\times2+3\times3=\boldsymbol{14}
$$

### (3) $\begin{bmatrix}4&3&1\\1&-2&3\\5&7&0\end{bmatrix}\begin{bmatrix}7\\2\\1\end{bmatrix}$
$$
=\begin{bmatrix}4\times7+3\times2+1\times1\\1\times7+(-2)\times2+3\times1\\5\times7+7\times2+0\times1\end{bmatrix}
=\boldsymbol{\begin{bmatrix}35\\6\\49\end{bmatrix}}
$$

### (4) $[x_1,\ x_2,\ x_3]
\begin{bmatrix}
a_{11}&a_{12}&a_{13}\\
a_{21}&a_{22}&a_{23}\\
a_{31}&a_{32}&a_{33}
\end{bmatrix}
\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}$
**思路**：二次型，先算后面乘法再左乘行向量
$$
=\boldsymbol{a_{11}x_1^2+a_{22}x_2^2+a_{33}x_3^2
+(a_{12}+a_{21})x_1x_2
+(a_{13}+a_{31})x_1x_3
+(a_{23}+a_{32})x_2x_3}
$$

### (5) $\begin{bmatrix}2&1&4&0\\1&-1&3&4\end{bmatrix}
\begin{bmatrix}
1&0&3&1\\
0&-1&0&2\\
1&-3&0&1\\
4&0&0&-2
\end{bmatrix}$
$$
=\boldsymbol{\begin{bmatrix}
6&-13&6&8\\
2&-8&3&-4
\end{bmatrix}}
$$

### (6) $\begin{bmatrix}
1&2&1&0\\
0&1&0&1\\
0&0&2&1\\
0&0&0&3
\end{bmatrix}
\begin{bmatrix}
1&0&3&1\\
0&1&2&-1\\
0&0&-2&3\\
0&0&0&-3
\end{bmatrix}$
$$
=\boldsymbol{\begin{bmatrix}
1&2&5&2\\
0&1&2&-4\\
0&0&-4&3\\
0&0&0&-9
\end{bmatrix}}
$$

---

## 4. $A=\begin{bmatrix}1&1\\0&1\end{bmatrix},\ B=\begin{bmatrix}1&0\\1&2\end{bmatrix}$，判断等式
先算出：
$$
AB=\begin{bmatrix}1&1\\0&1\end{bmatrix}\begin{bmatrix}1&0\\1&2\end{bmatrix}=\begin{bmatrix}2&2\\1&2\end{bmatrix}
$$
$$
BA=\begin{bmatrix}1&0\\1&2\end{bmatrix}\begin{bmatrix}1&1\\0&1\end{bmatrix}=\begin{bmatrix}1&1\\1&3\end{bmatrix}
$$
$$
A+B=\begin{bmatrix}2&1\\1&3\end{bmatrix},\quad A-B=\begin{bmatrix}0&1\\-1&-1\end{bmatrix}
$$
$$
A^2=\begin{bmatrix}1&2\\0&1\end{bmatrix},\quad B^2=\begin{bmatrix}1&0\\3&4\end{bmatrix}
$$

### (1) $\(AB=BA\)$
$AB=\begin{bmatrix}2&2\\1&2\end{bmatrix}\neq\begin{bmatrix}1&1\\1&3\end{bmatrix}=BA$，**不成立**。
> 知识点：矩阵乘法**一般不可交换**。

### (2) $(A+B)(A-B)=A^2-B^2$
左边：$(A+B)(A-B)=\begin{bmatrix}2&1\\1&3\end{bmatrix}\begin{bmatrix}0&1\\-1&-1\end{bmatrix}=\begin{bmatrix}-1&1\\-3&-2\end{bmatrix}$
右边：$A^2-B^2=\begin{bmatrix}1&2\\0&1\end{bmatrix}-\begin{bmatrix}1&0\\3&4\end{bmatrix}=\begin{bmatrix}0&2\\-3&-3\end{bmatrix}$
左右不等，**不成立**。
> 知识点：只有$\(AB=BA\)$时，才有$(A+B)(A-B)=A^2-B^2$。

### (3) $(A+B)^2=A^2+2AB+B^2$
左边：$(A+B)^2=\begin{bmatrix}2&1\\1&3\end{bmatrix}^2=\begin{bmatrix}5&5\\5&10\end{bmatrix}$
右边：$A^2+2AB+B^2=\begin{bmatrix}1&2\\0&1\end{bmatrix}+2\begin{bmatrix}2&2\\1&2\end{bmatrix}+\begin{bmatrix}1&0\\3&4\end{bmatrix}=\begin{bmatrix}6&6\\5&9\end{bmatrix}$
左右不等，**不成立**。
> 知识点：只有$\(AB=BA\)$时，才有$(A+B)^2=A^2+2AB+B^2$。

---

## 5. 举反例说明命题错误
> 思路：矩阵没有普通数的性质，找简单二阶矩阵反例

### (1) 若$A^2=O$，则$\(A=O\)$
反例：$A=\begin{bmatrix}0&1\\0&0\end{bmatrix}$
$$
A^2=\begin{bmatrix}0&1\\0&0\end{bmatrix}\begin{bmatrix}0&1\\0&0\end{bmatrix}=\begin{bmatrix}0&0\\0&0\end{bmatrix}=O,\ A\neq O
$$
命题错误。

### (2) 若$A^2=A$，则$\(A=O\)$或$\(A=E\)$
反例：$A=\begin{bmatrix}1&0\\0&0\end{bmatrix}$
$$
A^2=\begin{bmatrix}1&0\\0&0\end{bmatrix}\begin{bmatrix}1&0\\0&0\end{bmatrix}=\begin{bmatrix}1&0\\0&0\end{bmatrix}=A,\ A\neq O,A\neq E
$$
命题错误。

### (3) 若$\(AX=AY\)$且$A\neq O$，则$\(X=Y\)$
反例：
$$
A=\begin{bmatrix}1&0\\0&0\end{bmatrix},\ X=\begin{bmatrix}0&0\\1&0\end{bmatrix},\ Y=\begin{bmatrix}0&0\\0&0\end{bmatrix}
$$
$$
AX=\begin{bmatrix}0&0\\0&0\end{bmatrix},\ AY=\begin{bmatrix}0&0\\0&0\end{bmatrix},\ \(AX=AY\),A\neq O,X\neq Y
$$
命题错误。
> 知识点：矩阵乘法**无消去律**。

---

## 6. $A=\begin{bmatrix}\lambda&1&0\\0&\lambda&1\\0&0&\lambda\end{bmatrix}$，求$A^k$（$k$正整数）
**思路**：分解 $A=\lambda E+N,\ N=\begin{bmatrix}0&1&0\\0&0&1\\0&0&0\end{bmatrix}$，$N^3=O$，二项式展开（$\lambda E$与$N$可交换）
$$
A^k=(\lambda E+N)^k=\sum_{i=0}^k\mathrm{C}_k^i (\lambda E)^{k-i}N^i
$$
$N^1=\begin{bmatrix}0&1&0\\0&0&1\\0&0&0\end{bmatrix},\ N^2=\begin{bmatrix}0&0&1\\0&0&0\\0&0&0\end{bmatrix},\ N^3=N^4=\cdots=O$
$$
A^k=\lambda^kE + k\lambda^{k-1}N+\mathrm{C}_k^2\lambda^{k-2}N^2
$$
$$
\boldsymbol{A^k=\begin{bmatrix}
\lambda^k & k\lambda^{k-1} & \dfrac{k(k-1)}{2}\lambda^{k-2}\\
0 & \lambda^k & k\lambda^{k-1}\\
0 & 0 & \lambda^k
\end{bmatrix}}
$$

---

## 7. $A=\begin{bmatrix}2&-1&0\\1&3&1\end{bmatrix},\ B=\begin{bmatrix}2&1\\-3&5\\2&4\end{bmatrix}$，求$(AB)^T$与$B^T A^T$
**思路**：先算$AB$，再转置；利用转置定理$(AB)^T=B^T A^T$验证。
$$
AB=\begin{bmatrix}2&-1&0\\1&3&1\end{bmatrix}\begin{bmatrix}2&1\\-3&5\\2&4\end{bmatrix}=
\begin{bmatrix}7&-3\\-5&20\end{bmatrix}
$$
$$
(AB)^T=\boldsymbol{\begin{bmatrix}7&-5\\-3&20\end{bmatrix}}
$$
$$
B^T=\begin{bmatrix}2&-3&2\\1&5&4\end{bmatrix},\ A^T=\begin{bmatrix}2&1\\-1&3\\0&1\end{bmatrix}
$$
$$
B^T A^T=\begin{bmatrix}2&-3&2\\1&5&4\end{bmatrix}\begin{bmatrix}2&1\\-1&3\\0&1\end{bmatrix}=
\boldsymbol{\begin{bmatrix}7&-5\\-3&20\end{bmatrix}}
$$
两者相等，验证转置公式 $(AB)^T=B^T A^T$。

---

## 8. $\(A,B\)$为$n$阶方阵，$A$对称（$A^T=A$），证明$B^T AB$对称
**思路**：对称矩阵定义：证明$(B^T AB)^T=B^T AB$
$$
(B^T AB)^T = A^T (B^T)^T B^T = A^T B B^T
$$
已知$A^T=A$：
$$
(B^T AB)^T = A B^T B = B^T AB
$$
满足对称矩阵定义，故$B^T AB$是对称矩阵。

---

## 9. $\(A,B\)$都是$n$阶对称阵，证明：$AB$对称 $\iff \(AB=BA\)$
**思路**：双向证明，对称定义$M^T=M$，$(AB)^T=B^T A^T=BA$（因为$A^T=\(A,B\)^T=B$）

1. **必要性（$AB$对称 $\Rightarrow \(AB=BA\)$）**
若$AB$对称，则$(AB)^T=AB$。
又$(AB)^T=B^T A^T=BA$，故$\(AB=BA\)$。

2. **充分性（$\(AB=BA\) \Rightarrow AB$对称）**
已知$\(AB=BA\)$，
$$
(AB)^T=B^T A^T=BA=AB
$$
$(AB)^T=AB$，故$AB$对称。

综上，$AB$为对称阵的充要条件是$\(AB=BA\)$。

---

## 10. 分块矩阵计算
### (1)
$$
A=\begin{bmatrix}
1&-1&0&0&0\\
0&2&0&0&0\\
1&0&3&-1&1\\
-1&1&2&0&0\\
2&1&1&-1&1
\end{bmatrix},\quad
B=\begin{bmatrix}
3&1&1&-1&1\\
-2&0&0&2&1\\
0&0&1&-1&0\\
0&0&0&0&1\\
0&0&-1&1&1
\end{bmatrix}
$$
**分块**：
$$
A=\begin{bmatrix}A_{11}&O\\A_{21}&A_{22}\end{bmatrix},\quad
B=\begin{bmatrix}B_{11}&B_{12}\\O&B_{22}\end{bmatrix}
$$
$$
AB=\begin{bmatrix}A_{11}B_{11}&A_{11}B_{12}\\A_{21}B_{11}&A_{21}B_{12}+A_{22}B_{22}\end{bmatrix}
$$
$$
\boldsymbol{AB=
\begin{bmatrix}
5&1&1&-3&0\\
-4&0&0&4&2\\
3&1&3&-3&0\\
-5&-1&1&3&0\\
4&2&1&0&4
\end{bmatrix}}
$$

### (2)
$$
A=\begin{bmatrix}
1&0&1&0&0\\
0&2&-1&0&0\\
3&1&0&0&0\\
0&0&0&-2&0\\
0&0&0&0&-2
\end{bmatrix},\quad
B=\begin{bmatrix}
1&0&1&0&0\\
0&2&0&0&0\\
0&0&3&0&0\\
0&0&0&-1&3\\
0&0&0&4&2
\end{bmatrix}
$$
**分块**：
$$
A=\begin{bmatrix}A_{11}&O\\O&A_{22}\end{bmatrix},\ B=\begin{bmatrix}B_{11}&O\\O&B_{22}\end{bmatrix}
$$
对角分块方阵相乘，对角块分别相乘
$$
A_{11}=\begin{bmatrix}1&0&1\\0&2&-1\\3&1&0\end{bmatrix},\quad
B_{11}=\begin{bmatrix}1&0&1\\0&2&0\\0&0&3\end{bmatrix}
$$
$$
A_{22}=\begin{bmatrix}-2&0\\0&-2\end{bmatrix},\quad
B_{22}=\begin{bmatrix}-1&3\\4&2\end{bmatrix}
$$
$$
A_{11}B_{11}=\begin{bmatrix}1&0&4\\0&4&-3\\3&2&3\end{bmatrix},\quad
A_{22}B_{22}=\begin{bmatrix}2&-6\\-8&-4\end{bmatrix}
$$
$$
\boldsymbol{AB=
\begin{bmatrix}
1&0&4&0&0\\
0&4&-3&0&0\\
3&2&3&0&0\\
0&0&0&2&-6\\
0&0&0&-8&-4
\end{bmatrix}}
$$

---

如果你需要，我可以把这整套题整理成一页可直接抄写的精简版（只保留题号+最终答案，去掉推导）。