In [ ]:
import numpy as np

IPython console for SymPy 1.14.0 (Python 3.13.9-64-bit) (ground types: python)

These commands were executed:
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.14.0/



# 第1章 矩阵

## 矩阵的概念


【课本知识点】矩阵的定义；单位矩阵、对角矩阵、数量矩阵、上 / 下三角矩阵、对称矩阵的结构与性质。

### ✍️伴读札记

#### 🔢NumPy


In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.diag([2, 4, 6])

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [7]:
np.random.randint(0, 10, size=(3,3))

array([[5, 6, 1],
       [7, 5, 7],
       [0, 0, 5]])

## 矩阵的运算

【课本知识点】矩阵加法、数乘的定义与运算律（交换律、结合律、分配律）。

【课本知识点】矩阵乘法的定义、运算律（重点：不满足交换律）；方阵的幂运算规则。

### ✍️伴读札记



#### 🔢NumPy

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
K = 3
np.array_equal(K*(A+B), K*A + K*B)

True

矩阵乘法用@运算符或np.dot()

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

A@B, A.dot(B), B@A, B.dot(A)

(array([[ 4,  4],
        [10,  8]]),
 array([[ 4,  4],
        [10,  8]]),
 array([[ 2,  4],
        [ 7, 10]]),
 array([[ 2,  4],
        [ 7, 10]]))

方阵幂用np.linalg.matrix_power()

In [14]:
np.linalg.matrix_power(A, 3)

array([[ 37,  54],
       [ 81, 118]])

In [15]:
A.T, A.T.T

(array([[1, 3],
        [2, 4]]),
 array([[1, 2],
        [3, 4]]))


## 分块矩阵





### ✍️伴读札记




#### 🔢NumPy

In [25]:
A = np.array([[1,2,0,0], [3,4,0,0],
               [0,0,5,6], [0,0,7,8]]);A

array([[1, 2, 0, 0],
       [3, 4, 0, 0],
       [0, 0, 5, 6],
       [0, 0, 7, 8]])

In [27]:
A11 = A[:2,:2]; A12 = A[:2,2:]
A21 = A[2:,:2]; A22 = A[2:,2:]

In [26]:
B = np.array(
    [[1,0,0,0], [0,1,0,0],
     [0,0,2,0], [0,0,0,2]]);B

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2]])

In [28]:
B11 = B[:2,:2]; B12 = B[:2,2:]
B21 = B[2:,:2]; B22 = B[2:,2:]

In [30]:
block_res = np.zeros_like(A)
block_res[:2,:2] = A11 @ B11
block_res[2:,2:] = A22 @ B22

In [32]:
np.array_equal(A@B, block_res)

True

## 习题 1